using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DBFfintech_Interface_Portal
{
    class TopTransactions
    {

           
         
            public static string createHTMLString(DataSet dt)
            {
                // Render any HTML fragment or document to HTML

             



           
                DateTime now = DateTime.Now;
            StringBuilder htmlString = new StringBuilder();
            DataTable dt1 = new DataTable();
            string Fund = "";
                string AccountNum = "";

            

                htmlString.AppendLine("<html>");
                htmlString.AppendLine("<head>");
                htmlString.AppendLine("<title></title>");
                htmlString.AppendLine("<link rel='stylesheet' href='bootsrap.css' type='text/css'>");
                htmlString.AppendLine("<link rel='stylesheet' href='style.css' type='text/css'>");

                htmlString.AppendLine("</head>");
                htmlString.AppendLine("<body  id='content'> ");

                htmlString.AppendLine("<div id ='background'>");
                htmlString.AppendLine("<p id ='bg-text'>Confidential</p>");
                htmlString.AppendLine(" </div>");


                htmlString.AppendLine("<div >");


                htmlString.AppendLine("<div  style='font-family: 'Roboto', sans-serif;letter-spacing: 0.1em;'>");
                htmlString.AppendLine("<div >");
                htmlString.AppendLine("<div >");
                htmlString.AppendLine(" <div >");
                htmlString.AppendLine("<div>");
                htmlString.AppendLine("<div> ");
                htmlString.AppendLine("</div>");
                htmlString.AppendLine("<div>");

                htmlString.AppendLine("<div class='row'>");
                htmlString.AppendLine("</br>");

                htmlString.AppendLine("<div class='col-sm-8'  style='margin-top: 30px;'>");
                htmlString.AppendLine("<h6><b>Report : Daily Top Transactions Report</b></h6>");
                htmlString.AppendLine("<h6>");
                htmlString.AppendLine("<b>Report Date  :  </b>" + Convert.ToDateTime(now).ToString("dddd, dd MMMM yyyy") + "</h6>");
                htmlString.AppendLine("<h6><b>Generated By : IntegratorAML-Sesfont Technologies</b></h6>");
                htmlString.AppendLine("<h6>");
               
                htmlString.AppendLine("</div>");


                htmlString.AppendLine("</div>");


                htmlString.AppendLine("</div>");
                htmlString.AppendLine("</div>");

                htmlString.AppendLine("<div>");
                htmlString.AppendLine("<div class='row'>");
                htmlString.AppendLine("<div  class='col-sm-4'>");

                htmlString.AppendLine("</div>");
                htmlString.AppendLine("<div style='margin-top: 60px;' class='col-sm-4'>");
                htmlString.AppendLine("<img height='150px' style='display: block; margin-left: auto;  margin-right: auto;'  src='bsb.png'/>");
                htmlString.AppendLine("</div>");
                htmlString.AppendLine("<div class='col-sm-4'>");
                htmlString.AppendLine("</div>");


                htmlString.AppendLine("</div>");
                htmlString.AppendLine("</div>");

                htmlString.AppendLine("<div><h2><strong>Top 20 Deposits </strong></h2></div>");
                htmlString.AppendLine("<table class='table table-bordered mb-0'  style='width:100%;padding: 0.2rem; margin-top: 30px; border: solid 1px gray'>");
                htmlString.AppendLine("<thead style='font-weight: 400' class='thead-dark'>");


                htmlString.AppendLine("<tr>");
                htmlString.AppendLine("<th style='border: solid  gray 1px; padding: 0.2rem;' >Transaction #</th>");
                htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem;'>Name</th>");
                htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem;'>Description</th>");
                htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem; padding-right: 1.3rem; text-align: right;'>Amount(BWP)</th>");
                htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem; padding-right: 1.3rem; text-align: right;'>Transaction Date</th>");

                 htmlString.AppendLine("</tr>");
                htmlString.AppendLine("<tbody>");

                if (dt.Tables.Count > 1)
            {
                dt1 = dt.Tables[0];
                for (int i = 0; i < dt1.Rows.Count; i++)
                {
                    htmlString.AppendLine("<tr  >");
                    htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.3rem;'>" + dt1.Rows[i]["TrxRowID"].ToString() + "</th>");
                    htmlString.AppendLine("<td  style='border: solid gray 1px; padding: 0.3rem;'>" + dt1.Rows[i]["FirstName"].ToString() + " " + dt1.Rows[i]["LastName"].ToString() + "</td>");
                    htmlString.AppendLine("<td  style='border: solid gray 1px; padding: 0.3rem;'>" + dt1.Rows[i]["TrxDescription"].ToString() + "</td>");
                    htmlString.AppendLine("<td  style='border: solid gray 1px; text-align: right; padding: 0.3rem;'>" + String.Format("{0:N2}", Convert.ToDecimal(dt1.Rows[i]["TrxAmount"].ToString())));
                    htmlString.AppendLine("<td  style='border: solid gray 1px; padding: 0.2rem; padding-right: 1.3rem; text-align: right'>" + Convert.ToDateTime(dt1.Rows[i]["TrxDate"].ToString()).ToString("dddd, dd MMMM yyyy") + "</td>");

                    htmlString.AppendLine("</tr>");
                }
            }
               
            
               

            
                htmlString.AppendLine("</tbody>");
                htmlString.AppendLine("</table>");


            htmlString.AppendLine("<div style='margin-top:40px;'><h2><strong>Top 20 Withdrawals </strong></h2></div>");
            htmlString.AppendLine("<table class='table table-bordered mb-0'  style='width:100%;padding: 0.2rem; margin-top: 30px; border: solid 1px gray'>");
            htmlString.AppendLine("<thead style='font-weight: 400' class='thead-dark'>");


            htmlString.AppendLine("<tr>");
            htmlString.AppendLine("<th style='border: solid  gray 1px; padding: 0.2rem;' >Transaction #</th>");
            htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem;'>Name</th>");
            htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem;'>Description</th>");
            htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem; padding-right: 1.3rem; text-align: right;'>Amount(BWP)</th>");
            htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.2rem; padding-right: 1.3rem; text-align: right;'>Transaction Date</th>");

            htmlString.AppendLine("</tr>");
            htmlString.AppendLine("<tbody>");

            DataTable dt2 = new DataTable();

            if (dt.Tables.Count > 1)
            {
                dt2 = dt.Tables[1];
                for (int i = 0; i < dt2.Rows.Count; i++)
                {
                    htmlString.AppendLine("<tr  >");
                    htmlString.AppendLine("<th  style='border: solid gray 1px; padding: 0.3rem;'>" + dt2.Rows[i]["TrxRowID"].ToString() + "</td>");
                    htmlString.AppendLine("<td  style='border: solid gray 1px; padding: 0.3rem;'>" + dt2.Rows[i]["FirstName"].ToString() +" "+ dt2.Rows[i]["LastName"].ToString() +"</td>");
                    htmlString.AppendLine("<td  style='border: solid gray 1px; padding: 0.3rem;'>" + dt2.Rows[i]["TrxDescription"].ToString() + "</td>");
                    htmlString.AppendLine("<td  style='border: solid gray 1px; text-align: right; padding: 0.3rem;'>" + String.Format("{0:N2}", Convert.ToDecimal(dt2.Rows[i]["TrxAmount"].ToString())) );
                    htmlString.AppendLine("</td>");
                    htmlString.AppendLine("<td  style='border: solid gray 1px; padding: 0.2rem; padding-right: 1.3rem; text-align: right'>" +Convert.ToDateTime( dt2.Rows[i]["TrxDate"].ToString()).ToString("dddd, dd MMMM yyyy") + "</td>");

                    htmlString.AppendLine("</tr>");
                }
            }





            htmlString.AppendLine("</tbody>");
            htmlString.AppendLine("</table>");




            htmlString.AppendLine("</div>");
                htmlString.AppendLine("</div>");
                htmlString.AppendLine("</div>");


               
           
                htmlString.AppendLine("</div>");

                htmlString.AppendLine("</body>");
                htmlString.AppendLine("</html>");


                return htmlString.ToString();


            
        }
    }
}
